<head>
<link rel="STYLESHEET" type="text/css" href="img/style.css">
</head>
<?php
 include("config.php");
 include("functions.php");
 include("login.php");
?>
<script language=javascript>
function addc(sss) {
	var obj = document.getElementById("c"+sss);
	var inp = document.getElementById("cc");
	inp.value = inp.value+obj.innerHTML+",";
}
function remc(sss) {
	var obj = document.getElementById("c"+sss);
	var inp = document.getElementById("cc");
	inp.value = inp.value+"!"+obj.innerHTML+",";
}
</script>
<input id="cc" name="Name" type="text" style="width:95%;position:fixed;" value="ALL,">
<table border='1' cellpadding='4' width='100%'>
<tr background='img/bg_table.jpg'><td><strong>CC</strong></td><td><strong>Country Name</strong></td><td><strong>Opt.</strong></td></tr>
<tr style='background:#E0E0E0'><td id='c0'>AD</td><td>ANDORRA</td><td><span onclick='addc(0)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(0)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c1'>AE</td><td>UNITED ARAB EMIRATES</td><td><span onclick='addc(1)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(1)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c2'>AF</td><td>AFGHANISTAN</td><td><span onclick='addc(2)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(2)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c3'>AG</td><td>ANTIGUA AND BARBUDA</td><td><span onclick='addc(3)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(3)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c4'>AI</td><td>ANGUILLA</td><td><span onclick='addc(4)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(4)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c5'>AL</td><td>ALBANIA</td><td><span onclick='addc(5)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(5)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c6'>AM</td><td>ARMENIA</td><td><span onclick='addc(6)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(6)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c7'>AN</td><td>NETHERLANDS ANTILLES</td><td><span onclick='addc(7)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(7)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c8'>AO</td><td>ANGOLA</td><td><span onclick='addc(8)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(8)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c9'>AQ</td><td>ANTARCTICA</td><td><span onclick='addc(9)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(9)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c10'>AR</td><td>ARGENTINA</td><td><span onclick='addc(10)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(10)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c11'>AS</td><td>AMERICAN SAMOA</td><td><span onclick='addc(11)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(11)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c12'>AT</td><td>AUSTRIA</td><td><span onclick='addc(12)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(12)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c13'>AU</td><td>AUSTRALIA</td><td><span onclick='addc(13)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(13)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c14'>AW</td><td>ARUBA</td><td><span onclick='addc(14)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(14)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c15'>AZ</td><td>AZERBAIJAN</td><td><span onclick='addc(15)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(15)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c16'>BA</td><td>BOSNIA AND HERZEGOVINA</td><td><span onclick='addc(16)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(16)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c17'>BB</td><td>BARBADOS</td><td><span onclick='addc(17)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(17)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c18'>BD</td><td>BANGLADESH</td><td><span onclick='addc(18)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(18)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c19'>BE</td><td>BELGIUM</td><td><span onclick='addc(19)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(19)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c20'>BF</td><td>BURKINA FASO</td><td><span onclick='addc(20)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(20)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c21'>BG</td><td>BULGARIA</td><td><span onclick='addc(21)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(21)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c22'>BH</td><td>BAHRAIN</td><td><span onclick='addc(22)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(22)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c23'>BI</td><td>BURUNDI</td><td><span onclick='addc(23)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(23)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c24'>BJ</td><td>BENIN</td><td><span onclick='addc(24)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(24)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c25'>BM</td><td>BERMUDA</td><td><span onclick='addc(25)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(25)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c26'>BN</td><td>BRUNEI DARUSSALAM</td><td><span onclick='addc(26)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(26)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c27'>BO</td><td>BOLIVIA</td><td><span onclick='addc(27)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(27)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c28'>BR</td><td>BRAZIL</td><td><span onclick='addc(28)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(28)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c29'>BS</td><td>BAHAMAS</td><td><span onclick='addc(29)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(29)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c30'>BT</td><td>BHUTAN</td><td><span onclick='addc(30)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(30)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c31'>BW</td><td>BOTSWANA</td><td><span onclick='addc(31)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(31)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c32'>BY</td><td>BELARUS</td><td><span onclick='addc(32)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(32)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c33'>BZ</td><td>BELIZE</td><td><span onclick='addc(33)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(33)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c34'>CA</td><td>CANADA</td><td><span onclick='addc(34)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(34)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c35'>CD</td><td>THE DEMOCRATIC REPUBLIC OF THE CONGO</td><td><span onclick='addc(35)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(35)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c36'>CF</td><td>CENTRAL AFRICAN REPUBLIC</td><td><span onclick='addc(36)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(36)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c37'>CG</td><td>CONGO</td><td><span onclick='addc(37)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(37)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c38'>CH</td><td>SWITZERLAND</td><td><span onclick='addc(38)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(38)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c39'>CI</td><td>COTE D'IVOIRE</td><td><span onclick='addc(39)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(39)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c40'>CK</td><td>COOK ISLANDS</td><td><span onclick='addc(40)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(40)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c41'>CL</td><td>CHILE</td><td><span onclick='addc(41)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(41)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c42'>CM</td><td>CAMEROON</td><td><span onclick='addc(42)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(42)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c43'>CN</td><td>CHINA</td><td><span onclick='addc(43)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(43)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c44'>CO</td><td>COLOMBIA</td><td><span onclick='addc(44)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(44)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c45'>CR</td><td>COSTA RICA</td><td><span onclick='addc(45)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(45)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c46'>CS</td><td>SERBIA AND MONTENEGRO</td><td><span onclick='addc(46)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(46)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c47'>CU</td><td>CUBA</td><td><span onclick='addc(47)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(47)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c48'>CV</td><td>CAPE VERDE</td><td><span onclick='addc(48)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(48)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c49'>CY</td><td>CYPRUS</td><td><span onclick='addc(49)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(49)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c50'>CZ</td><td>CZECH REPUBLIC</td><td><span onclick='addc(50)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(50)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c51'>DE</td><td>GERMANY</td><td><span onclick='addc(51)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(51)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c52'>DJ</td><td>DJIBOUTI</td><td><span onclick='addc(52)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(52)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c53'>DK</td><td>DENMARK</td><td><span onclick='addc(53)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(53)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c54'>DM</td><td>DOMINICA</td><td><span onclick='addc(54)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(54)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c55'>DO</td><td>DOMINICAN REPUBLIC</td><td><span onclick='addc(55)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(55)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c56'>DZ</td><td>ALGERIA</td><td><span onclick='addc(56)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(56)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c57'>EC</td><td>ECUADOR</td><td><span onclick='addc(57)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(57)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c58'>EE</td><td>ESTONIA</td><td><span onclick='addc(58)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(58)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c59'>EG</td><td>EGYPT</td><td><span onclick='addc(59)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(59)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c60'>ER</td><td>ERITREA</td><td><span onclick='addc(60)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(60)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c61'>ES</td><td>SPAIN</td><td><span onclick='addc(61)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(61)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c62'>ET</td><td>ETHIOPIA</td><td><span onclick='addc(62)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(62)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c63'>FI</td><td>FINLAND</td><td><span onclick='addc(63)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(63)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c64'>FJ</td><td>FIJI</td><td><span onclick='addc(64)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(64)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c65'>FK</td><td>FALKLAND ISLANDS (MALVINAS)</td><td><span onclick='addc(65)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(65)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c66'>FM</td><td>FEDERATED STATES OF MICRONESIA</td><td><span onclick='addc(66)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(66)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c67'>FO</td><td>FAROE ISLANDS</td><td><span onclick='addc(67)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(67)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c68'>FR</td><td>FRANCE</td><td><span onclick='addc(68)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(68)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c69'>GA</td><td>GABON</td><td><span onclick='addc(69)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(69)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c70'>GB</td><td>UNITED KINGDOM</td><td><span onclick='addc(70)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(70)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c71'>GD</td><td>GRENADA</td><td><span onclick='addc(71)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(71)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c72'>GE</td><td>GEORGIA</td><td><span onclick='addc(72)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(72)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c73'>GF</td><td>FRENCH GUIANA</td><td><span onclick='addc(73)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(73)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c74'>GH</td><td>GHANA</td><td><span onclick='addc(74)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(74)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c75'>GI</td><td>GIBRALTAR</td><td><span onclick='addc(75)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(75)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c76'>GL</td><td>GREENLAND</td><td><span onclick='addc(76)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(76)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c77'>GM</td><td>GAMBIA</td><td><span onclick='addc(77)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(77)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c78'>GN</td><td>GUINEA</td><td><span onclick='addc(78)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(78)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c79'>GP</td><td>GUADELOUPE</td><td><span onclick='addc(79)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(79)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c80'>GQ</td><td>EQUATORIAL GUINEA</td><td><span onclick='addc(80)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(80)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c81'>GR</td><td>GREECE</td><td><span onclick='addc(81)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(81)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c82'>GS</td><td>SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS</td><td><span onclick='addc(82)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(82)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c83'>GT</td><td>GUATEMALA</td><td><span onclick='addc(83)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(83)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c84'>GU</td><td>GUAM</td><td><span onclick='addc(84)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(84)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c85'>GW</td><td>GUINEA-BISSAU</td><td><span onclick='addc(85)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(85)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c86'>GY</td><td>GUYANA</td><td><span onclick='addc(86)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(86)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c87'>HK</td><td>HONG KONG</td><td><span onclick='addc(87)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(87)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c88'>HN</td><td>HONDURAS</td><td><span onclick='addc(88)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(88)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c89'>HR</td><td>CROATIA</td><td><span onclick='addc(89)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(89)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c90'>HT</td><td>HAITI</td><td><span onclick='addc(90)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(90)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c91'>HU</td><td>HUNGARY</td><td><span onclick='addc(91)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(91)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c92'>ID</td><td>INDONESIA</td><td><span onclick='addc(92)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(92)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c93'>IE</td><td>IRELAND</td><td><span onclick='addc(93)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(93)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c94'>IL</td><td>ISRAEL</td><td><span onclick='addc(94)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(94)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c95'>IN</td><td>INDIA</td><td><span onclick='addc(95)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(95)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c96'>IO</td><td>BRITISH INDIAN OCEAN TERRITORY</td><td><span onclick='addc(96)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(96)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c97'>IQ</td><td>IRAQ</td><td><span onclick='addc(97)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(97)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c98'>IR</td><td>ISLAMIC REPUBLIC OF IRAN</td><td><span onclick='addc(98)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(98)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c99'>IS</td><td>ICELAND</td><td><span onclick='addc(99)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(99)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c100'>IT</td><td>ITALY</td><td><span onclick='addc(100)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(100)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c101'>JM</td><td>JAMAICA</td><td><span onclick='addc(101)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(101)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c102'>JO</td><td>JORDAN</td><td><span onclick='addc(102)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(102)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c103'>JP</td><td>JAPAN</td><td><span onclick='addc(103)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(103)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c104'>KE</td><td>KENYA</td><td><span onclick='addc(104)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(104)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c105'>KG</td><td>KYRGYZSTAN</td><td><span onclick='addc(105)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(105)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c106'>KH</td><td>CAMBODIA</td><td><span onclick='addc(106)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(106)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c107'>KI</td><td>KIRIBATI</td><td><span onclick='addc(107)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(107)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c108'>KM</td><td>COMOROS</td><td><span onclick='addc(108)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(108)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c109'>KN</td><td>SAINT KITTS AND NEVIS</td><td><span onclick='addc(109)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(109)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c110'>KR</td><td>REPUBLIC OF KOREA</td><td><span onclick='addc(110)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(110)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c111'>KW</td><td>KUWAIT</td><td><span onclick='addc(111)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(111)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c112'>KY</td><td>CAYMAN ISLANDS</td><td><span onclick='addc(112)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(112)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c113'>KZ</td><td>KAZAKHSTAN</td><td><span onclick='addc(113)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(113)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c114'>LA</td><td>LAO PEOPLE'S DEMOCRATIC REPUBLIC</td><td><span onclick='addc(114)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(114)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c115'>LB</td><td>LEBANON</td><td><span onclick='addc(115)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(115)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c116'>LC</td><td>SAINT LUCIA</td><td><span onclick='addc(116)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(116)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c117'>LI</td><td>LIECHTENSTEIN</td><td><span onclick='addc(117)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(117)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c118'>LK</td><td>SRI LANKA</td><td><span onclick='addc(118)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(118)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c119'>LR</td><td>LIBERIA</td><td><span onclick='addc(119)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(119)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c120'>LS</td><td>LESOTHO</td><td><span onclick='addc(120)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(120)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c121'>LT</td><td>LITHUANIA</td><td><span onclick='addc(121)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(121)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c122'>LU</td><td>LUXEMBOURG</td><td><span onclick='addc(122)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(122)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c123'>LV</td><td>LATVIA</td><td><span onclick='addc(123)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(123)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c124'>LY</td><td>LIBYAN ARAB JAMAHIRIYA</td><td><span onclick='addc(124)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(124)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c125'>MA</td><td>MOROCCO</td><td><span onclick='addc(125)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(125)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c126'>MC</td><td>MONACO</td><td><span onclick='addc(126)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(126)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c127'>MD</td><td>REPUBLIC OF MOLDOVA</td><td><span onclick='addc(127)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(127)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c128'>MG</td><td>MADAGASCAR</td><td><span onclick='addc(128)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(128)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c129'>MH</td><td>MARSHALL ISLANDS</td><td><span onclick='addc(129)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(129)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c130'>MK</td><td>THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA</td><td><span onclick='addc(130)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(130)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c131'>ML</td><td>MALI</td><td><span onclick='addc(131)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(131)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c132'>MM</td><td>MYANMAR</td><td><span onclick='addc(132)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(132)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c133'>MN</td><td>MONGOLIA</td><td><span onclick='addc(133)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(133)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c134'>MO</td><td>MACAO</td><td><span onclick='addc(134)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(134)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c135'>MP</td><td>NORTHERN MARIANA ISLANDS</td><td><span onclick='addc(135)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(135)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c136'>MQ</td><td>MARTINIQUE</td><td><span onclick='addc(136)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(136)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c137'>MR</td><td>MAURITANIA</td><td><span onclick='addc(137)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(137)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c138'>MT</td><td>MALTA</td><td><span onclick='addc(138)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(138)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c139'>MU</td><td>MAURITIUS</td><td><span onclick='addc(139)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(139)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c140'>MV</td><td>MALDIVES</td><td><span onclick='addc(140)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(140)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c141'>MW</td><td>MALAWI</td><td><span onclick='addc(141)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(141)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c142'>MX</td><td>MEXICO</td><td><span onclick='addc(142)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(142)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c143'>MY</td><td>MALAYSIA</td><td><span onclick='addc(143)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(143)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c144'>MZ</td><td>MOZAMBIQUE</td><td><span onclick='addc(144)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(144)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c145'>NA</td><td>NAMIBIA</td><td><span onclick='addc(145)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(145)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c146'>NC</td><td>NEW CALEDONIA</td><td><span onclick='addc(146)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(146)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c147'>NE</td><td>NIGER</td><td><span onclick='addc(147)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(147)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c148'>NF</td><td>NORFOLK ISLAND</td><td><span onclick='addc(148)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(148)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c149'>NG</td><td>NIGERIA</td><td><span onclick='addc(149)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(149)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c150'>NI</td><td>NICARAGUA</td><td><span onclick='addc(150)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(150)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c151'>NL</td><td>NETHERLANDS</td><td><span onclick='addc(151)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(151)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c152'>NO</td><td>NORWAY</td><td><span onclick='addc(152)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(152)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c153'>NP</td><td>NEPAL</td><td><span onclick='addc(153)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(153)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c154'>NR</td><td>NAURU</td><td><span onclick='addc(154)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(154)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c155'>NU</td><td>NIUE</td><td><span onclick='addc(155)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(155)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c156'>NZ</td><td>NEW ZEALAND</td><td><span onclick='addc(156)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(156)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c157'>OM</td><td>OMAN</td><td><span onclick='addc(157)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(157)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c158'>PA</td><td>PANAMA</td><td><span onclick='addc(158)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(158)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c159'>PE</td><td>PERU</td><td><span onclick='addc(159)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(159)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c160'>PF</td><td>FRENCH POLYNESIA</td><td><span onclick='addc(160)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(160)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c161'>PG</td><td>PAPUA NEW GUINEA</td><td><span onclick='addc(161)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(161)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c162'>PH</td><td>PHILIPPINES</td><td><span onclick='addc(162)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(162)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c163'>PK</td><td>PAKISTAN</td><td><span onclick='addc(163)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(163)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c164'>PL</td><td>POLAND</td><td><span onclick='addc(164)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(164)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c165'>PR</td><td>PUERTO RICO</td><td><span onclick='addc(165)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(165)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c166'>PS</td><td>PALESTINIAN TERRITORY, OCCUPIED</td><td><span onclick='addc(166)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(166)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c167'>PT</td><td>PORTUGAL</td><td><span onclick='addc(167)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(167)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c168'>PW</td><td>PALAU</td><td><span onclick='addc(168)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(168)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c169'>PY</td><td>PARAGUAY</td><td><span onclick='addc(169)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(169)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c170'>QA</td><td>QATAR</td><td><span onclick='addc(170)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(170)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c171'>RE</td><td>REUNION</td><td><span onclick='addc(171)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(171)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c172'>RO</td><td>ROMANIA</td><td><span onclick='addc(172)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(172)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c173'>RU</td><td>RUSSIAN FEDERATION</td><td><span onclick='addc(173)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(173)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c174'>RW</td><td>RWANDA</td><td><span onclick='addc(174)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(174)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c175'>SA</td><td>SAUDI ARABIA</td><td><span onclick='addc(175)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(175)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c176'>SB</td><td>SOLOMON ISLANDS</td><td><span onclick='addc(176)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(176)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c177'>SC</td><td>SEYCHELLES</td><td><span onclick='addc(177)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(177)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c178'>SD</td><td>SUDAN</td><td><span onclick='addc(178)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(178)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c179'>SE</td><td>SWEDEN</td><td><span onclick='addc(179)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(179)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c180'>SG</td><td>SINGAPORE</td><td><span onclick='addc(180)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(180)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c181'>SI</td><td>SLOVENIA</td><td><span onclick='addc(181)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(181)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c182'>SK</td><td>SLOVAKIA</td><td><span onclick='addc(182)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(182)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c183'>SL</td><td>SIERRA LEONE</td><td><span onclick='addc(183)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(183)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c184'>SM</td><td>SAN MARINO</td><td><span onclick='addc(184)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(184)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c185'>SN</td><td>SENEGAL</td><td><span onclick='addc(185)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(185)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c186'>SO</td><td>SOMALIA</td><td><span onclick='addc(186)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(186)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c187'>SR</td><td>SURINAME</td><td><span onclick='addc(187)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(187)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c188'>ST</td><td>SAO TOME AND PRINCIPE</td><td><span onclick='addc(188)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(188)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c189'>SV</td><td>EL SALVADOR</td><td><span onclick='addc(189)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(189)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c190'>SY</td><td>SYRIAN ARAB REPUBLIC</td><td><span onclick='addc(190)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(190)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c191'>SZ</td><td>SWAZILAND</td><td><span onclick='addc(191)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(191)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c192'>TD</td><td>CHAD</td><td><span onclick='addc(192)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(192)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c193'>TG</td><td>TOGO</td><td><span onclick='addc(193)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(193)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c194'>TH</td><td>THAILAND</td><td><span onclick='addc(194)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(194)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c195'>TJ</td><td>TAJIKISTAN</td><td><span onclick='addc(195)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(195)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c196'>TK</td><td>TOKELAU</td><td><span onclick='addc(196)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(196)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c197'>TL</td><td>TIMOR-LESTE</td><td><span onclick='addc(197)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(197)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c198'>TM</td><td>TURKMENISTAN</td><td><span onclick='addc(198)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(198)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c199'>TN</td><td>TUNISIA</td><td><span onclick='addc(199)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(199)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c200'>TO</td><td>TONGA</td><td><span onclick='addc(200)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(200)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c201'>TR</td><td>TURKEY</td><td><span onclick='addc(201)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(201)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c202'>TT</td><td>TRINIDAD AND TOBAGO</td><td><span onclick='addc(202)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(202)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c203'>TV</td><td>TUVALU</td><td><span onclick='addc(203)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(203)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c204'>TW</td><td>TAIWAN</td><td><span onclick='addc(204)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(204)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c205'>TZ</td><td>UNITED REPUBLIC OF TANZANIA</td><td><span onclick='addc(205)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(205)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c206'>UA</td><td>UKRAINE</td><td><span onclick='addc(206)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(206)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c207'>UG</td><td>UGANDA</td><td><span onclick='addc(207)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(207)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c208'>UM</td><td>UNITED STATES MINOR OUTLYING ISLANDS</td><td><span onclick='addc(208)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(208)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c209'>US</td><td>UNITED STATES</td><td><span onclick='addc(209)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(209)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c210'>UY</td><td>URUGUAY</td><td><span onclick='addc(210)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(210)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c211'>UZ</td><td>UZBEKISTAN</td><td><span onclick='addc(211)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(211)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c212'>VA</td><td>HOLY SEE (VATICAN CITY STATE)</td><td><span onclick='addc(212)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(212)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c213'>VC</td><td>SAINT VINCENT AND THE GRENADINES</td><td><span onclick='addc(213)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(213)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c214'>VE</td><td>VENEZUELA</td><td><span onclick='addc(214)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(214)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c215'>VG</td><td>VIRGIN ISLANDS, BRITISH</td><td><span onclick='addc(215)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(215)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c216'>VI</td><td>VIRGIN ISLANDS, U.S.</td><td><span onclick='addc(216)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(216)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c217'>VN</td><td>VIET NAM</td><td><span onclick='addc(217)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(217)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c218'>VU</td><td>VANUATU</td><td><span onclick='addc(218)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(218)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c219'>WS</td><td>SAMOA</td><td><span onclick='addc(219)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(219)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c220'>YE</td><td>YEMEN</td><td><span onclick='addc(220)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(220)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c221'>YT</td><td>MAYOTTE</td><td><span onclick='addc(221)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(221)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c222'>ZA</td><td>SOUTH AFRICA</td><td><span onclick='addc(222)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(222)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#FFFFFF'><td id='c223'>ZM</td><td>ZAMBIA</td><td><span onclick='addc(223)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(223)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
<tr style='background:#E0E0E0'><td id='c224'>ZW</td><td>ZIMBABWE</td><td><span onclick='addc(224)' style='cursor: pointer; padding:1px; background: #DBF7F9; font-size:10px;border:1px solid #B2B2B2'>ADD</span>&nbsp;<span onclick='remc(224)' style='cursor: pointer; padding:1px; background: #FEDC9A; font-size:10px;border:1px solid #B2B2B2'>REM</span></td></tr>
</table>
<?php

?>